# Generated by Django 5.2.7 on 2025-10-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.link')),
            ],
            options={
                'verbose_name_plural': 'Click Stats',
                'db_table': 'click_stats',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['link', '-clicked_at'], name='click_stats_link_id_92d026_idx')],
            },
        ),
    ]
