# Generated by Django 5.2.7 on 2025-10-30 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('custom_alias', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('original_url', models.URLField(max_length=2048)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='links_short_c_95d67d_idx'), models.Index(fields=['custom_alias'], name='links_custom__1666b1_idx'), models.Index(fields=['user', '-created_at'], name='links_user_id_feaab0_idx')],
            },
        ),
    ]
